### ISSUE TITLE
roi values - why two?

### ISSUE THREAD

**Issue by satra** [gablab/murfi2#12]
for every mask murfi appears to return two values for each TR. what are these two values?

**Comment by ohinds** [comment]
What do you mean by "return"? I only see one value printed on the command line. Also, can you provide the config file and EPI series where this was observed?

**Comment by satra** [comment]
only on the scanner, which sends both prospective and retrospective scans. if servenii is updated to handle two series to mimic the scanner, then we can test it with two series. i'll try to update the python server as well.

**Comment by ohinds** [comment]
Prospective and retrospective to what?

**Comment by satra** [comment]
the data coming from vsend involves both the prospective volume and the retrospective recon volume. so every TR it sends two volumes.

**Comment by ohinds** [comment]
I'm sorry, I still don't get what they are prospective and retrospective to.

**Comment by satra** [comment]
prospective and retrospective motion correction - this is from the PACEWARP sequences.

**Comment by ohinds** [comment]
Oh! Yeah, there is already a config flag for that. Add this to your scanner section:
<option name="onlyReadMoCo"> true </option>

**Comment by satra** [comment]
roger!

**Comment by satra** [comment]
talking of these options - where would i head to see the current set of options? i think we should have a commented single neurofeedback.xml with all available options.

**Comment by ohinds** [comment]
This has a list of processing modules and the associated options. I can whip something up for scanner options.

http://mindhive.mit.edu/realtime/murfi/configuration/modules
