### ISSUE TITLE
servenii: command not found

### ISSUE THREAD

**Issue by cccbauer** [gablab/murfi2#36]
Hi Satra,

I installed murfi afresh on a new laptop but am getting

`servenii: command not found`

when trying to run the `./servedata.sh' script

**Comment by satra** [comment]
pinging @ohinds - he has been refactoring all of this repo.

**Comment by ohinds** [comment]
sorry about that, @cccbauer, the documentation is missing a step. to allow the ./servedata.sh script to find the servenii executable, first you need to execute 
```export PATH=$PATH:<path to murfi directory>/util/scanner_sim```
where you replace <path to murfi directory> with the actual path. 

you only have to do this once in the shell you are executing the servedata.sh script from. 

also, you can put that line in your .bashrc file and you won't have to manually adjust the path in the future.

**Comment by ohinds** [comment]
yup, and it is in the docker image. i'm working on instructions for docker / singularity now.
