### ISSUE TITLE
config file minimal requirements

### ISSUE THREAD

**Issue by satra** [gablab/murfi2#9]
the qt branch minimal config file is not minimal.

the xml file needs a few more things amongst others:
```
disabled=false
port number
receiveimages=true
```

also, the config file requires the subject info for murfi to load it, even if environment variables are set.

**Comment by ohinds** [comment]
This is resolved in the qt branch. It was an issue where configs weren't being handled the same way if the config file was loaded via the GUI vs specified on the command line.
